export const FETCH_PETS = "FETCH_PETS";
export const FETCH_PET = "FETCH_PET";
export const FETCH_FEEDINGS = "FETCH_FEEDINGS";
export const UPDATE_FEEDING = "UPDATE_FEEDING";
export const UPDATE_FEEDING_PET = "UPDATE_FEEDING_PET";
export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUP_PETS = "FETCH_GROUP_PETS";
export const ADD_PET = "ADD_PET"; // Add this line
export const UPDATE_PET = "UPDATE_PET";
// actionTypes.js
export const ADD_PET_TO_GROUP = "ADD_PET_TO_GROUP";
export const FETCH_GROUPS_FOR_PETS = "FETCH_GROUPS_FOR_PETS";
export const REMOVE_PET_FROM_GROUP = "REMOVE_PET_FROM_GROUP";
export const ADD_FEEDING = "ADD_FEEDING"; // ✅ Add this if missing
export const ADD_GROUP = "ADD_GROUP";
export const DELETE_PET = "DELETE_PET";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const FETCH_USER = "FETCH_USER";
export const UPDATE_USER = "UPDATE_USER";

export const FETCH_FREEZER_ITEMS = "FETCH_FREEZER_ITEMS";
export const ADD_FREEZER_ITEM = "ADD_FREEZER_ITEM";
export const DELETE_FREEZER_ITEM = "DELETE_FREEZER_ITEM";
export const UPDATE_FREEZER_ITEM = "UPDATE_FREEZER_ITEM";
export const LINK_FEEDING_TO_FREEZER = "LINK_FEEDING_TO_FREEZER";
export const FETCH_FEEDING_FREEZER_LINKS = "FETCH_FEEDING_FREEZER_LINKS";
export const SET_LOW_STOCK_WARNINGS = "SET_LOW_STOCK_WARNINGS";
