export const PREY_TYPES = [
  {
    category: "Mouse",
    options: [
      "Pinky Mouse",
      "Fuzzy Mouse",
      "Weanling Mouse",
      "Small Mouse",
      "Medium Mouse",
      "Large Mouse",
      "XL Mouse",
    ],
  },
  {
    category: "Rat",
    options: [
      "Pinky Rat",
      "Fuzzy Rat",
      "Weanling Rat",
      "Small Rat",
      "Medium Rat",
      "Large Rat",
      "XL Rat",
      "Jumbo Rat",
    ],
  },
  {
    category: "Insects",
    options: [
      "Cricket",
      "Mealworm",
      "Superworm",
      "Dubia Roach",
      "Hornworm",
      "Waxworm",
      "Silkworm",
      "Phoenix Worm (BSFL)",
      "Isopods",
    ],
  },
  {
    category: "Diets",
    options: ["Crested Gecko Diet"],
  },
  {
    category: "Vegetables",
    options: [
      "Collard Greens",
      "Mustard Greens",
      "Dandelion Greens",
      "Kale",
      "Butternut Squash",
      "Carrots",
      "Bell Peppers",
      "Zucchini",
      "Sweet Potato",
    ],
  },
  {
    category: "Fruits",
    options: [
      "Mango",
      "Papaya",
      "Banana",
      "Blueberries",
      "Strawberries",
      "Peach",
      "Figs",
      "Watermelon",
    ],
  },
  {
    category: "Other",
    options: ["Other (Enter custom prey type)"],
  },
];
