name: Android Detox E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  detox-android:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: google_apis
          avd-name: Pixel_9_API_35
          disable-animations: true
          script: echo "Emulator ready"

      - name: Run E2E Tests
        run: npm run ci:e2e
        env:
          JAVA_HOME: /usr/libexec/java_home
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
