name: Android Detox E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  detox-android:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      ANDROID_EMULATOR_USE_SYSTEM_LIBS: 1  # Critical for Apple Silicon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Install Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;34.0.0"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-35;google_apis;arm64-v8a"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: arm64-v8a  # Changed to ARM for Apple Silicon
          profile: pixel_9
          target: google_apis
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-snapshot
          script: |
            adb start-server
            echo "Waiting for device..."
            adb wait-for-device
            
            # Wait for full boot completion
            until adb shell getprop sys.boot_completed | grep "1"; do
              sleep 5
              echo "Still waiting for boot..."
            done
            
            # Disable animations
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            adb shell input keyevent 82

      - name: Build and Test
        run: |
          npm run build:e2e
          npm run test:e2e
        env:
          JAVA_HOME: /usr/libexec/java_home
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}