name: Run Maestro Tests

on:
  pull_request:
    branches:
      - main

jobs:
  maestro-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install Android SDK and ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk adb
          echo "Android SDK Installed"

      - name: Set up Android Emulator
        run: |
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser `whoami` libvirt
          sudo adduser `whoami` kvm
          echo "Starting AVD..."
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          echo "Android Emulator Path: $ANDROID_HOME/emulator"
          echo "Available AVDs:"
          avdmanager list avd || echo "No AVDs found"
          nohup emulator -avd test -no-audio -no-window &
          adb wait-for-device
          adb devices

      - name: Run Maestro Tests
        run: |
          maestro test maestro/home.yml
          maestro test maestro/expand_test.yml
