name: Preview & Maestro Tests

on: pull_request

jobs:
  preview:
    name: EAS Update Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "EXPO_TOKEN secret is required!"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create Preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto

  maestro-tests:
    name: Maestro Android Tests
    needs: preview # Wait for preview job first
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.1

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: |
            # Install Expo Go for SDK 52 (verify URL!)
            curl -L -o expo-go.apk https://dpq5q02fu5f55.cloudfront.net/Exponent-2.28.3.apk
            adb install expo-go.apk

            # Start Expo tunnel
            npm install -g expo-cli  # Needed for SDK 52
            nohup expo start --tunnel > expo.log 2>&1 &

            # Wait for tunnel
            sleep 45

            # Run Maestro tests
            maestro test maestro/
