name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  detox-ios:
    runs-on: macos-latest # Use macOS runner for iOS testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Install Apple dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils  # Required for managing iOS simulators

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Run Expo Prebuild (Generate ios/ directory)
        run: expo prebuild

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App for Detox
        run: detox build --configuration ios.sim.debug

      - name: Run Detox tests for iOS
        run: detox test --configuration ios.sim.debug
