name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm test

  detox-android:
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      ANDROID_EMULATOR_USE_SYSTEM_LIBS: 1
      ADB_INSTALL_TIMEOUT: 20
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: |
          npm ci
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator"

      - name: Android Emulator Setup
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: arm64-v8a
          profile: pixel_6
          target: google_apis
          channel: stable
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-snapshot -no-accel
          script: |
            adb start-server
            npm run build:android
            npx detox build -c android.emu.debug

            # Custom emulator boot check
            echo "Waiting for emulator..."
            $ANDROID_HOME/platform-tools/adb wait-for-device
            while [ "$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do
              sleep 5
              echo "Still waiting..."
            done

            echo "Emulator ready. Connected devices:"
            adb devices -l

            npx detox test -c android.emu.debug --headless --loglevel trace
