name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm test

  detox-android:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          ndk: 21.4.7075529
      - name: Install dependencies
        run: npm install
      - name: Build Android app
        run: npm run build:android
      - name: Prepare AVD
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;default;x86"
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-30;default;x86" --force
      - name: Start Emulator
        run: |
          sudo apt-get install -y libgl1-mesa-dev
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -accel on &
          adb wait-for-device
          adb shell input keyevent 82 &
      - name: Install `.aab` on Emulator
        run: |
          bundletool build-apks --bundle=votrack.aab --output=votrack.apks --mode=universal --ks=debug.keystore --ks-pass=pass:android --ks-key-alias=androiddebugkey --key-pass=pass:android
          unzip votrack.apks -d votrack_apks
          adb install votrack_apks/universal.apk
      - name: Detox Build
        run: npm run build:e2e
      - name: Run Detox tests
        run: npm run test:e2e
