name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm test

  detox-android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Install dependencies
        run: npm ci

      - name: Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: arm64-b8a
          profile: pixel_6
          script: |
            npm run build:android
            npx detox build -c android.emu.debug
            npx detox test -c android.emu.debug --headless
