name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  detox-android:
    runs-on: ubuntu-latest # Use Ubuntu since we are only testing Android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_30_x86 -no-window &
          adb wait-for-device

      - name: Build Android App for Detox
        run: detox build --configuration a
