name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm test

  detox-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - name: Install Android SDK & Emulator
        run: |
          # ... JDK installation steps ...

          # Install Android SDK
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chown $USER:$USER /usr/local/lib/android/sdk
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          mv cmdline-tools/* /usr/local/lib/android/sdk/cmdline-tools/latest/
          rm -rf cmdline-tools

          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator" "system-images;android-30;google_apis;x86_64"

      - name: Create and start emulator
        run: |
          export ANDROID_AVD_HOME="$HOME/.android/avd"
          mkdir -p $ANDROID_AVD_HOME

          echo "no" | avdmanager create avd \
            -n Pixel_3a_API_30_x86 \
            -k "system-images;android-30;google_apis;x86_64" \
            --force

          nohup emulator -avd Pixel_3a_API_30_x86 -no-audio -no-window -no-boot-anim -gpu swiftshader_indirect &

          adb wait-for-device
          adb -e shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - run: npm install -g detox-cli
      - run: detox build --configuration android.metro.debug
      - run: detox test --configuration android.metro.debug
